# Generated by Django 5.1.3 on 2024-11-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="введите имя автора",
                        max_length=50,
                        verbose_name="полное имя автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=100,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="введите описание",
                        max_length=300,
                        null=True,
                        verbose_name="описание",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        help_text="укажите количество книг в наличии",
                        verbose_name="количество книг в наличии",
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        help_text="укажите автора",
                        related_name="author_book",
                        to="book.author",
                        verbose_name="автор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="укажите собственника",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
            },
        ),
    ]
