# Generated by Django 5.1.3 on 2024-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                help_text="укажите автора", to="book.author", verbose_name="автор"
            ),
        ),
    ]
