# Generated by Django 5.1.3 on 2024-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_remove_book_author_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="укажите количество книг в наличии",
                verbose_name="количество книг в наличии",
            ),
        ),
    ]
