# Generated by Django 5.1.3 on 2024-11-27 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_genre_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                help_text="укажите жанр книги",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.genre",
                verbose_name="жанр",
            ),
        ),
    ]
