# Generated by Django 5.1.3 on 2024-11-30 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_author_full_name_alter_genre_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="count",
        ),
        migrations.AlterField(
            model_name="book",
            name="owner",
            field=models.ForeignKey(
                help_text="укажите библиотекаря",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.CreateModel(
            name="BookItem",
            fields=[
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Введите инвентарный номер",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Инвентарный номер",
                    ),
                ),
                (
                    "book_details",
                    models.ForeignKey(
                        help_text="Введите название книги",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.book",
                        verbose_name="Название книги",
                    ),
                ),
                (
                    "keeper",
                    models.ForeignKey(
                        default=None,
                        help_text="Выберите владельца",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экземпляр книги",
                "verbose_name_plural": "Экземпляры книги",
            },
        ),
    ]
