# Generated by Django 5.1.3 on 2024-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_alter_bookitem_keeper"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="укажите количество книг в наличии",
                verbose_name="количество книг в наличии",
            ),
        ),
    ]
