# Generated by Django 5.1.3 on 2024-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_remove_book_count_bookitem_status_alter_book_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookitem",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes"),
        ),
    ]
